version: '2'
services:
    littletimmy-app:
        image: littletimmy
        external_links:
            - littletimmy-mysql:mysql
            - littletimmy-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/littletimmy?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    littletimmy-mysql:
        extends:
            file: mysql.yml
            service: littletimmy-mysql
    littletimmy-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: littletimmy-elasticsearch
